<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-QS3L28C" failures="1" tests="12" name="LoginTest_PF" time="140.947" errors="0" timestamp="2022-09-05T17:03:09 IST">
  <testcase classname="tests_PF.ExecuteTests_PF" name="Test_OpenWebsite" time="48.592"/>
  <testcase classname="tests_PF.ExecuteTests_PF" name="Test_Username" time="12.743"/>
  <testcase classname="tests_PF.ExecuteTests_PF" name="Test_Password" time="6.944"/>
  <testcase classname="tests_PF.ExecuteTests_PF" name="Validate_Username" time="7.54">
    <failure type="java.lang.AssertionError" message="expected [Please provide your full ] but found [Please provide your full name]">
      <![CDATA[java.lang.AssertionError: expected [Please provide your full ] but found [Please provide your full name]
at pages_PF.DemoPage1_PF.checkUsernameErrorMessage(DemoPage1_PF.java:67)
at tests_PF.ExecuteTests_PF.Validate_Username(ExecuteTests_PF.java:49)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1510)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- Validate_Username -->
  <testcase classname="tests_PF.ExecuteTests_PF" name="Validate_Password" time="6.779"/>
  <testcase classname="tests_PF.ExecuteTests_PF" name="TestLogin_ValidInput" time="9.163"/>
  <testcase classname="tests_PF.ExecuteTests2_PF" name="Test_PageUrl" time="0.121"/>
  <testcase classname="tests_PF.ExecuteTests2_PF" name="Test_Country" time="16.017"/>
  <testcase classname="tests_PF.ExecuteTests2_PF" name="Test_Address" time="9.223"/>
  <testcase classname="tests_PF.ExecuteTests2_PF" name="Test_Email" time="8.964"/>
  <testcase classname="tests_PF.ExecuteTests2_PF" name="Test_Phone" time="8.78"/>
  <testcase classname="tests_PF.ExecuteTests2_PF" name="Test_Submit_Details" time="3.366"/>
</testsuite> <!-- LoginTest_PF -->
